import tkinter as tk
from tkinter import filedialog, messagebox, ttk
import requests
import base64
import threading
import json
from PIL import Image, ImageTk
import os
from datetime import datetime

ENV_PATH = ".env"

DEFAULT_API_PROMPT = (
    "Du siehst ein Foto eines Kassenzettels (Quittung) aus einem Geschäft.\n"
    "Deine Aufgabe ist es, ALLE Informationen vollständig und exakt aus dem Bild zu übertragen (OCR + strukturierte Extraktion).\n"
    "WICHTIG: Erfinde keine Werte. Wenn etwas unleserlich ist, gib null an und setze ein Feld \"confidence\" auf \"low\" sowie eine kurze Notiz im Feld \"notes\".\n\n"
    "Gib das Ergebnis ausschließlich als gültiges JSON zurück (ohne Markdown, ohne Codeblock, ohne zusätzliche Erklärung).\n\n"
    "Extrahiere so vollständig wie möglich:\n"
    "1) Händlerdaten: merchant_name, merchant_address, merchant_phone, store_id/branch_id, vat_id/tax_id\n"
    "2) Belegdaten: receipt_number, date (YYYY-MM-DD), time, currency (z.B. EUR), payment_method\n"
    "3) Positionen (am wichtigsten): line_items in Reihenfolge. Für jede Position: description, quantity, unit_price, total_price, item_code/sku/ean, tax_rate, discount, confidence, raw_text\n"
    "4) Summen & Steuern: subtotal, tax_total, taxes[], discounts_total, tip, total\n"
    "5) Zusätzliche Daten: loyalty_id, cashier_id, terminal_id, notes[]\n\n"
    "Regeln: Dezimalpunkt im JSON, Währungszeichen aus Zahlen entfernen, Reihenfolge bewahren, Inkonsistenzen in notes notieren."
)


def _strip_quotes(v: str) -> str:
    v = v.strip()
    if len(v) >= 2 and ((v[0] == '"' and v[-1] == '"') or (v[0] == "'" and v[-1] == "'")):
        return v[1:-1]
    return v


def load_env(path: str = ENV_PATH) -> dict:
    """Liest einfache KEY=VALUE Paare aus einer .env Datei. Keine externe Abhängigkeit nötig."""
    env = {}
    if not os.path.exists(path):
        return env
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = _strip_quotes(v)
    return env


def save_env_value(key: str, value: str, path: str = ENV_PATH) -> None:
    """Schreibt/aktualisiert einen KEY in der .env Datei, erstellt die Datei falls nötig."""
    key = key.strip()
    value = "" if value is None else str(value)

    env = load_env(path)
    env[key] = value

    # Stabil schreiben (einfaches Format)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by OpenRouterVisionApp\n")
        for k in sorted(env.keys()):
            v = env[k].replace("\n", " ")
            # In Quotes setzen, damit Sonderzeichen (z.B. :) unkritisch sind
            f.write(f"{k}=\"{v}\"\n")


class OpenRouterVisionApp:
    def __init__(self, root):
        self.root = root
        self.root.title("OpenRouter Vision & OCR Analyzer")
        self.root.geometry("800x800")
        self.root.configure(padx=20, pady=20)

        self.image_path = None
        self.photo = None  # Referenz für das angezeigte Bild aufbewahren

        # Werte aus .env laden (falls vorhanden)
        self.env = load_env()

        self._create_widgets()

        # Nach dem Widget-Setup: geladene Werte in UI setzen
        self._apply_env_to_ui()

        # Auto-Persistenz aktivieren
        self._bind_persistence()

    def _create_widgets(self):
        # --- API Konfiguration ---
        frame_api = ttk.LabelFrame(self.root, text="1. Konfiguration", padding=(10, 10))
        frame_api.pack(fill=tk.X, pady=(0, 10))

        ttk.Label(frame_api, text="OpenRouter API Key:").grid(row=0, column=0, sticky=tk.W, pady=5)
        self.api_key_entry = ttk.Entry(frame_api, width=50, show="*")
        self.api_key_entry.grid(row=0, column=1, sticky=tk.W, pady=5, padx=5)

        ttk.Label(frame_api, text="Modell auswählen:").grid(row=1, column=0, sticky=tk.W, pady=5)
        ttk.Label(frame_api, text="Modell (OpenRouter ID):").grid(row=1, column=0, sticky=tk.W, pady=5)
        # Freitext, damit du exakt die Model-ID eingeben kannst, die in deinem OpenRouter-Account verfügbar ist.
        # Beispiel: openai/gpt-4o
        self.model_entry = ttk.Entry(frame_api, width=50)
        self.model_entry.insert(0, "openai/gpt-4o")
        self.model_entry.grid(row=1, column=1, sticky=tk.W, pady=5, padx=5)

        # --- Bildauswahl ---
        frame_image = ttk.LabelFrame(self.root, text="2. Bildauswahl", padding=(10, 10))
        frame_image.pack(fill=tk.X, pady=(0, 10))

        self.btn_select_img = ttk.Button(frame_image, text="Bild vom Computer auswählen", command=self.select_image)
        self.btn_select_img.pack(pady=5)

        self.lbl_image = tk.Label(frame_image, text="Kein Bild ausgewählt", bg="#e0e0e0", width=40, height=10)
        self.lbl_image.pack(pady=5)

        # --- Prompt/Anweisung ---
        frame_prompt = ttk.LabelFrame(self.root, text="3. Analyse-Anweisung (Prompt)", padding=(10, 10))
        frame_prompt.pack(fill=tk.X, pady=(0, 10))

        self.prompt_entry = tk.Text(frame_prompt, height=3, width=80)
        self.prompt_entry.insert(tk.END, "Bitte extrahiere alle Texte aus diesem Bild (OCR) und behalte das Layout bei.")
        self.prompt_entry.pack(fill=tk.BOTH, pady=5)

        # --- Ausführung & Ergebnis ---
        frame_result = ttk.LabelFrame(self.root, text="4. Ergebnis", padding=(10, 10))
        frame_result.pack(fill=tk.BOTH, expand=True)

        self.btn_analyze = ttk.Button(frame_result, text="Bild jetzt analysieren", command=self.start_analysis)
        self.btn_analyze.pack(pady=5)

        self.status_var = tk.StringVar()
        self.status_var.set("Bereit.")
        self.lbl_status = ttk.Label(frame_result, textvariable=self.status_var, foreground="blue")
        self.lbl_status.pack(pady=5)

        # Scrollbare Textbox für das Ergebnis
        scroll_y = tk.Scrollbar(frame_result)
        scroll_y.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.result_text = tk.Text(frame_result, height=15, yscrollcommand=scroll_y.set, wrap=tk.WORD)
        self.result_text.pack(fill=tk.BOTH, expand=True)
        scroll_y.config(command=self.result_text.yview)

    def _apply_env_to_ui(self):
        """Lädt API-Key, Model und Prompt aus .env in die UI (falls vorhanden)."""
        api_key = (self.env.get("OPENROUTER_API_KEY") or "").strip()
        model = (self.env.get("OPENROUTER_MODEL") or "").strip()
        prompt = self.env.get("API_PROMPT")

        if api_key:
            self.api_key_entry.delete(0, tk.END)
            self.api_key_entry.insert(0, api_key)

        if model:
            self.model_entry.delete(0, tk.END)
            self.model_entry.insert(0, model)

        # Prompt: aus .env, sonst Default setzen und direkt persistieren
        if prompt is None or not str(prompt).strip():
            prompt = DEFAULT_API_PROMPT
            save_env_value("API_PROMPT", prompt)
            self.env["API_PROMPT"] = prompt

        # Prompt-Textbox befüllen
        self.prompt_entry.delete("1.0", tk.END)
        self.prompt_entry.insert(tk.END, str(prompt))

    def _bind_persistence(self):
        """Speichert API-Key/Model/Prompt automatisch in .env, sobald sich die Felder ändern."""
        self._save_timer = None

        def schedule_save(*_):
            # Debounce: nicht bei jedem Tastendruck sofort schreiben
            if self._save_timer is not None:
                try:
                    self.root.after_cancel(self._save_timer)
                except Exception:
                    pass
            self._save_timer = self.root.after(500, self._persist_settings)

        # Bei jeder Änderung (Key Release) speichern (debounced)
        self.api_key_entry.bind("<KeyRelease>", schedule_save)
        self.model_entry.bind("<KeyRelease>", schedule_save)

        # Prompt-Textbox: bei Änderungen speichern (debounced)
        self.prompt_entry.bind("<KeyRelease>", schedule_save)

        # Zusätzlich beim Verlassen des Feldes sofort speichern
        self.api_key_entry.bind("<FocusOut>", lambda e: self._persist_settings())
        self.model_entry.bind("<FocusOut>", lambda e: self._persist_settings())
        self.prompt_entry.bind("<FocusOut>", lambda e: self._persist_settings())

    def _persist_settings(self):
        """Schreibt die aktuellen Werte in die .env Datei."""
        api_key = self.api_key_entry.get().strip()
        model = self.model_entry.get().strip()
        prompt = self.prompt_entry.get("1.0", tk.END).strip()

        if api_key != (self.env.get("OPENROUTER_API_KEY") or ""):
            save_env_value("OPENROUTER_API_KEY", api_key)
            self.env["OPENROUTER_API_KEY"] = api_key

        if model != (self.env.get("OPENROUTER_MODEL") or ""):
            save_env_value("OPENROUTER_MODEL", model)
            self.env["OPENROUTER_MODEL"] = model

        if prompt != (self.env.get("API_PROMPT") or ""):
            save_env_value("API_PROMPT", prompt)
            self.env["API_PROMPT"] = prompt

    def select_image(self):
        """Öffnet einen Dateidialog zur Auswahl eines Bildes und zeigt eine Vorschau an."""
        file_path = filedialog.askopenfilename(
            title="Bild auswählen",
            filetypes=[("Bilder", "*.png;*.jpg;*.jpeg;*.webp")]
        )
        if file_path:
            self.image_path = file_path
            try:
                # Vorschau erstellen (max 300x300 Pixel für GUI)
                img = Image.open(self.image_path)
                img.thumbnail((300, 300))
                self.photo = ImageTk.PhotoImage(img)
                self.lbl_image.config(image=self.photo, text="", width=img.width, height=img.height)
                self.status_var.set(f"Bild geladen: {os.path.basename(self.image_path)}")
            except Exception as e:
                messagebox.showerror("Fehler", f"Bild konnte nicht geladen werden:\n{e}")

    def start_analysis(self):
        """Validiert die Eingaben und startet den API-Aufruf in einem separaten Thread."""
        api_key = self.api_key_entry.get().strip()
        model = self.model_entry.get().strip()
        prompt = self.prompt_entry.get("1.0", tk.END).strip()

        if not api_key:
            messagebox.showwarning("Fehlende Eingabe", "Bitte gib einen OpenRouter API Key ein.")
            return
        if not self.image_path:
            messagebox.showwarning("Fehlende Eingabe", "Bitte wähle zuerst ein Bild aus.")
            return
        if not prompt:
            messagebox.showwarning("Fehlende Eingabe", "Bitte gib einen Prompt ein.")
            return

        # UI aktualisieren
        self.btn_analyze.config(state=tk.DISABLED)
        self.result_text.delete("1.0", tk.END)
        self.status_var.set("Analysiere Bild... Bitte warten.")

        # Thread starten, damit die GUI nicht einfriert
        threading.Thread(target=self._run_api_request, args=(api_key, model, prompt, self.image_path), daemon=True).start()

    def _run_api_request(self, api_key, model, prompt, img_path):
        """Führt den eigentlichen Netzwerkaufruf aus (läuft im Hintergrund-Thread)."""
        try:
            # 1. Bild in Base64 kodieren
            with open(img_path, "rb") as img_file:
                base64_image = base64.b64encode(img_file.read()).decode('utf-8')
            
            # MIME-Type anhand der Dateiendung ermitteln (vereinfacht)
            ext = img_path.lower().split('.')[-1]
            mime_type = "image/jpeg" if ext in ["jpg", "jpeg"] else f"image/{ext}"

            # 2. Header & Payload für OpenRouter vorbereiten
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://github.com/openrouter-ocr", # Empfohlen von OpenRouter
                "X-Title": "Python Desktop OCR"
            }

            payload = {
                "model": model,
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": prompt
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": f"data:{mime_type};base64,{base64_image}"
                                }
                            }
                        ]
                    }
                ]
            }

            # 3. Request senden
            response = requests.post(
                url="https://openrouter.ai/api/v1/chat/completions",
                headers=headers,
                json=payload,
                timeout=60 # Timeout auf 60 Sekunden setzen für große Bilder
            )
            
            # Status prüfen
            response.raise_for_status()
            data = response.json()

            # Vollständige API-Antwort im Terminal ausgeben (Debug/Transparenz)
            print("=== OpenRouter API Response ===")
            print(json.dumps(data, indent=2, ensure_ascii=False))
            print("===============================")

            # Ergebnis extrahieren
            result_text = data['choices'][0]['message']['content']

            # Token-Nutzung (falls vom Provider zurückgegeben)
            usage = data.get('usage') or {}
            prompt_tokens = usage.get('prompt_tokens')
            completion_tokens = usage.get('completion_tokens')
            total_tokens = usage.get('total_tokens')

            token_info = ""
            if prompt_tokens is not None or completion_tokens is not None or total_tokens is not None:
                token_info = f" | Tokens: prompt={prompt_tokens}, completion={completion_tokens}, total={total_tokens}"
            else:
                token_info = " | Tokens: (nicht verfügbar für dieses Modell/Provider)"

            # Ergebnis automatisch mit Zeitstempel speichern
            out_dir = "ocr_results"
            os.makedirs(out_dir, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            out_path = os.path.join(out_dir, f"ocr_result_{timestamp}.txt")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(result_text)

            status_msg = f"Erfolgreich gespeichert: {out_path}{token_info}"

            # Update GUI (muss im Main-Thread passieren, daher after verwenden)
            self.root.after(0, self._update_result_ui, result_text, status_msg)

        except requests.exceptions.HTTPError as http_err:
            error_msg = f"HTTP Fehler: {http_err}"
            # Versuche detaillierte Fehlermeldung von OpenRouter zu lesen
            try:
                err_json = response.json()
                if "error" in err_json:
                    error_msg += f"\nDetails: {err_json['error'].get('message', '')}"
            except json.JSONDecodeError:
                pass
            self.root.after(0, self._handle_error_ui, error_msg)
            
        except requests.exceptions.ConnectionError:
            self.root.after(0, self._handle_error_ui, "Verbindungsfehler: Bitte prüfe deine Internetverbindung.")
        except requests.exceptions.Timeout:
            self.root.after(0, self._handle_error_ui, "Zeitüberschreitung: Die API hat zu lange für eine Antwort gebraucht.")
        except Exception as e:
            self.root.after(0, self._handle_error_ui, f"Unerwarteter Fehler:\n{str(e)}")

    def _update_result_ui(self, result_text, status_msg):
        """Schreibt das Ergebnis in die GUI und aktiviert den Button wieder."""
        self.result_text.insert(tk.END, result_text)
        self.status_var.set(status_msg)
        self.btn_analyze.config(state=tk.NORMAL)

    def _handle_error_ui(self, error_msg):
        """Zeigt Fehler in der GUI an."""
        self.status_var.set("Fehler bei der Analyse!")
        self.btn_analyze.config(state=tk.NORMAL)
        messagebox.showerror("API Fehler", error_msg)


if __name__ == "__main__":
    root = tk.Tk()
    app = OpenRouterVisionApp(root)
    root.mainloop()
